model:
  vit:
    in_channels: 3
    embedding_dim: 192
    patch_size: 16
    max_patch_num: 4096
    depth: 6
    n_heads: 8
    mlp_size: 768
  cls:
    n_classes: 5

model_weights:
  vit_backbone: "model_weights/vit_backbone.pth"
  classifier: "model_weights/classifier.pth"
  
training:
  num_epochs: 30
  warmup_epochs: 3
  batch_size: 128
  lr: 1e-4
  use_amp: True
  device: "cuda"

